# Notebook de adquisición de datos — SECOP II Pereira

## Proyecto de Minería de Datos

**Pregunta de negocio:**

¿Qué patrones y posibles anomalías estadísticas se presentan en los montos, modalidades y concentración de proveedores en la contratación pública de Pereira registrada en SECOP II, y cómo esta información permite a la **Oficina de Control Interno de la Alcaldía de Pereira** pasar de auditorías aleatorias posteriores a una **priorización preventiva y focalizada de auditorías especiales** sobre los contratos con montos atípicos o contratistas hiperconcentrados antes de autorizar adiciones presupuestales o actas de liquidación?

## Objetivo del notebook

Este notebook tiene como propósito adquirir, preparar y cruzar dos fuentes oficiales de datos de SECOP II para el municipio de Pereira, Risaralda:

1. SECOP II — Procesos de Contratación.
2. SECOP II — Contratos Electrónicos.

El cruce relacional se realiza utilizando como llave confirmada el identificador del proceso de compra: la columna **`id_del_portafolio`** en la fuente de Procesos y la columna **`proceso_de_compra`** en la fuente de Contratos.

In [ ]:
import pandas as pd
import requests
from io import StringIO

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [ ]:
URL_PROCESOS = "https://www.datos.gov.co/resource/p6dx-8zbt.json"

params_procesos = {
    "$limit": 50000,
    "$where": "upper(ciudad_entidad) = 'PEREIRA'"
}

respuesta = requests.get(URL_PROCESOS, params=params_procesos)

print("Código de respuesta:", respuesta.status_code)

respuesta.raise_for_status()

procesos = pd.DataFrame(respuesta.json())

print("Fuente 1 - Procesos de Contratación")
print("Filas:", procesos.shape[0])
print("Columnas:", procesos.shape[1])

procesos.head()

Código de respuesta: 200
Fuente 1 - Procesos de Contratación
Filas: 50000
Columnas: 57

,entidad,nit_entidad,departamento_entidad,ciudad_entidad,ordenentidad,codigo_pci,id_del_proceso,referencia_del_proceso,ppi,id_del_portafolio,nombre_del_procedimiento,descripci_n_del_procedimiento,fase,fecha_de_publicacion_del,fecha_de_ultima_publicaci,fecha_de_publicacion_fase_3,precio_base,modalidad_de_contratacion,justificaci_n_modalidad_de,duracion,unidad_de_duracion,ciudad_de_la_unidad_de,nombre_de_la_unidad_de,proveedores_invitados,proveedores_con_invitacion,visualizaciones_del,proveedores_que_manifestaron,respuestas_al_procedimiento,respuestas_externas,conteo_de_respuestas_a_ofertas,proveedores_unicos_con,numero_de_lotes,estado_del_procedimiento,id_estado_del_procedimiento,adjudicado,id_adjudicacion,codigoproveedor,departamento_proveedor,ciudad_proveedor,valor_total_adjudicacion,nombre_del_adjudicador,nombre_del_proveedor,nit_del_proveedor_adjudicado,codigo_principal_de_categoria,estado_de_apertura_del_proceso,tipo_de_contrato,subtipo_de_contrato,categorias_adicionales,urlproceso,codigo_entidad,estado_resumen,fecha_de_publicacion_fase_2,fecha_de_recepcion_de,fecha_de_apertura_de_respuesta,fecha_de_apertura_efectiva,fecha_adjudicacion,fecha_de_publicacion
0,UNIVERSIDAD TECNOLÓGICA DE PEREIRA,891480035,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.3293809,8085-2022,700445026,CO1.BDOS.3207380,Prestación de servicios profesionales como For...,No definido,Presentación de oferta,2022-08-30T00:00:00.000,2022-08-30T00:00:00.000,2022-08-30T00:00:00.000,13500000,Contratación régimen especial,Regla aplicable,0,día(s),Pereira,GESTIÓN DE LA CONTRATACIÓN-UNIVERSIDAD TECNOLÓ...,0,0,0,0,0,0,0,0,0,Publicado,50,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.80111701,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,700445026,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN
1,AREA METROPOLITANA CENTRO OCCIDENTE,891410902,Risaralda,Pereira,Territorial,Centralizada,CO1.REQ.2659965,CD-39-2022,703244210,CO1.BDOS.2586857,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,PRESTAR LOS SERVICIOS DE APOYO A LA GESTIÓN EN...,Presentación de oferta,2022-01-17T00:00:00.000,2022-01-17T00:00:00.000,2022-01-17T00:00:00.000,7200000,Contratación directa,Servicios profesionales y apoyo a la gestión,4,Mes(es),Pereira,Contratación Directa AMCO - 1,0,0,0,0,0,0,0,0,0,Seleccionado,70,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.80161504,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,703244210,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN
2,CONCEJO MUNICIPAL DE PEREIRA,816002478,Risaralda,Pereira,Territorial,Centralizada,CO1.REQ.6615293,CMP-CPSAG-66-2024,705853745,CO1.BDOS.6490218,APOYO A LA GESTION,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTION ...,Presentación de oferta,2024-08-05T00:00:00.000,2024-08-05T00:00:00.000,2024-08-05T00:00:00.000,4500000,Contratación directa,Servicios profesionales y apoyo a la gestión,3,Mes(es),Pereira,CONTRATACIÓN CONCEJO MUNICIPAL DE PEREIRA,0,0,0,0,0,0,0,0,0,Seleccionado,70,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.83112200,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,705853745,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN
3,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.3542690,SMDSP-CD-7447-2022,702259557,CO1.BDOS.3451485,PRESTAR LOS SERVICIOS PROFESIONALES PARA LA EJ...,PRESTAR LOS SERVICIOS PROFESIONALES PARA LA EJ...,Presentación de oferta,2022-10-28T00:00:00.000,2022-10-28T00:00:00.000,2022-10-28T00:00:00.000,7980000,Contratación directa,Servicios profesionales y apoyo a la gestión,2,Mes(es),Pereira,SECRETARIA DESARROLLO SOCIAL Y POLÍTICO,0,0,0,0,0,0,0,0,0,Seleccionado,70,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.80111701,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,702259557,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN
4,UNIVERSIDAD TECNOLÓGICA DE PEREIRA,891480035,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.4732912,7037-2023,700445026,CO1.BDOS.4627267,Prestación de servicios profesionales para apo...,Prestación de servicios profesionales para apo...,Presentación de oferta,2023-06-26T00:00:00.000,2023-06-26T00:00:00.000,2023-06-26T00:00:00.000,15000000,Contratación régimen especial,Regla aplicable,0,día(s),Pereira,GESTIÓN DE LA CONTRATACIÓN-UNIVERSIDAD TECNOLÓ...,0,0,0,0,0,0,0,0,0,Publicado,50,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.80111701,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,700445026,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
URL_CONTRATOS = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

params_contratos = {
    "$limit": 50000,
    "$where": "upper(ciudad) = 'PEREIRA'"
}

respuesta_contratos = requests.get(
    URL_CONTRATOS,
    params=params_contratos
)

print("Código de respuesta:", respuesta_contratos.status_code)

respuesta_contratos.raise_for_status()

contratos = pd.DataFrame(respuesta_contratos.json())

print("Fuente 2 - Contratos Electrónicos")
print("Filas:", contratos.shape[0])
print("Columnas:", contratos.shape[1])

contratos.head()

Código de respuesta: 200
Fuente 2 - Contratos Electrónicos
Filas: 50000
Columnas: 95

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,id_contrato,referencia_del_contrato,estado_contrato,codigo_de_categoria_principal,descripcion_del_proceso,tipo_de_contrato,modalidad_de_contratacion,justificacion_modalidad_de,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,condiciones_de_entrega,tipodocproveedor,documento_proveedor,proveedor_adjudicado,es_grupo,es_pyme,habilita_pago_adelantado,liquidaci_n,obligaci_n_ambiental,obligaciones_postconsumo,reversion,origen_de_los_recursos,destino_gasto,valor_del_contrato,valor_de_pago_adelantado,valor_facturado,valor_pendiente_de_pago,valor_pagado,valor_amortizado,valor_pendiente_de,valor_pendiente_de_ejecucion,saldo_cdp,saldo_vigencia,espostconflicto,dias_adicionados,puntos_del_acuerdo,pilares_del_acuerdo,urlproceso,nombre_representante_legal,nacionalidad_representante_legal,domicilio_representante_legal,tipo_de_identificaci_n_representante_legal,identificaci_n_representante_legal,g_nero_representante_legal,presupuesto_general_de_la_nacion_pgn,sistema_general_de_participaciones,sistema_general_de_regal_as,recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_,recursos_de_credito,recursos_propios,codigo_entidad,codigo_proveedor,objeto_del_contrato,duraci_n_del_contrato,nombre_del_banco,tipo_de_cuenta,n_mero_de_cuenta,el_contrato_puede_ser_prorrogado,nombre_ordenador_del_gasto,tipo_de_documento_ordenador_del_gasto,n_mero_de_documento_ordenador_del_gasto,nombre_supervisor,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,direcci_n_de_ejecuci_n_del_contrato,criterios_de_sostenibilidad_ambiental,requisitos_ambientales_en_las_especificaciones_t_cnicas,criterios_ambientales_en_la_evaluaci_n_de_las_ofertas,obligaciones_contractuales_o_poscontractuales_a_nivel_ambiental,uso_de_etiquetado_ecol_gico,obligaciones_posconsumo,ultima_actualizacion,fecha_de_notificaci_n_de_prorrogaci_n,fecha_inicio_liquidacion,fecha_fin_liquidacion,fecha_inicio_reversi_n,fecha_fin_reversi_n,fecha_inicio_obligaciones_posconsumo,fecha_fin_obligaciones_posconsumo
0,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.4655229,CO1.PCCNTR.5164661,4173-2023,En ejecución,V1.80111701,PRESTAR LOS SERVICIOS DE APOYO A LA GESTION PA...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2023-06-28T00:00:00.000,2023-06-30T00:00:00.000,2023-12-29T00:00:00.000,No Definido,Cédula de Ciudadanía,41106868,BEATRIZ ELENA AVILEZ TRUJILLO,No,No,No,No,No,No,No,Distribuido,Inversión,10806000,0,10806000,0,10806000,0,0,0,10806000,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,BEATRIZ ELENA AVILEZ TRUJILLO,CO,No Definido,Sin Descripcion,Sin Descripcion,Mujer,0,0,0,10806000,0,0,702259557,722465838,PRESTAR LOS SERVICIOS DE APOYO A LA GESTION PA...,6 Mes(es),BANCOLOMBIA,Ahorros,85187248235,No,ANGELA MARIA RUBIO MEJIA,Cédula de Ciudadanía,42137679,JOHN JAIRO VELASQUEZ GUERRA,Cédula de Ciudadanía,6894878,JOHN JAIRO VELASQUEZ GUERRA,Cédula de Ciudadanía,6894878,No,No definido,Cr 7 No. 18-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MEGABÚS S.A.,816007837,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Transporte,Ejecutivo,Centralizada,CO1.BDOS.3692285,CO1.PCCNTR.4367024,002-2023,terminado,V1.80111701,Prestación de servicios profesionales en el ap...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2023-01-05T00:00:00.000,2023-01-05T00:00:00.000,2023-12-31T00:00:00.000,Como acordado previamente,Cédula de Ciudadanía,9955803,LUIS FERNANDO ANGEL VALLE,No,No,No,No,No,No,No,Recursos Propios,Funcionamiento,40800000,0,40347667,452333,40347667,0,0,452333,40800000,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,LUIS FERNANDO ANGEL VALLE,CO,cr 10 # 17 -55,Cédula de Ciudadanía,9955803,Hombre,0,0,0,0,0,40800000,707893285,708292016,Prestación de servicios profesionales en el ap...,12 Mes(es),BANCOLOMBIA,Ahorros,85240206469,No,DARIO FERNANDO ACOSTA CHAMORRO,Cédula de Ciudadanía,79.558.204.,Mauricio Ospina Hincapié,Cédula de Ciudadanía,10009141,No definido,No definido,No definido,No,No definido,Cr 10 17-50 P-9 Edificio Torre Central\nPereir...,No definido,No definido,No definido,No definido,No definido,No,2024-03-08T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.4661383,CO1.PCCNTR.5172157,4255-2023,Modificado,V1.80101510,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2023-06-28T00:00:00.000,2023-07-04T00:00:00.000,2023-12-31T00:00:00.000,NXTWY.DLVY.2,Cédula de Ciudadanía,1010034213,leiner stiven mejia aricapa,No,No,No,No,No,No,No,Distribuido,Inversión,11392000,0,9596160,1795840,9596160,0,0,1795840,11392000,0,No,28,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,leiner stiven mejia aricapa,CO,No Definido,Sin Descripcion,Sin Descripcion,Hombre,0,0,0,11392000,0,0,702259557,722468600,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,178 Dia(s),bancolombia,Ahorros,11521018056,Si,Monica Patricia Botero Montoya,Cédula de Ciudadanía,42155861,ALEXANDER GALINDO LÓPEZ,Cédula de Ciudadanía,1088254973,Monica Patricia Botero Montoya,Cédula de Ciudadanía,42155861,No,No definido,Cr 7 No. 18-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2023-12-01T00:00:00.000,2023-12-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN
3,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.2404408,CO1.PCCNTR.3061614,5771-2021,Cerrado,V1.82111900,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2021-11-26T00:00:00.000,2021-11-29T00:00:00.000,2021-12-18T00:00:00.000,A convenir,NIT,860509265,Semana S.A.,No,No,No,No,No,No,No,Distribuido,Inversión,19635000,0,19635000,0,19635000,0,0,0,50000000,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,LIGIA YANETH GÓMEZ CUÉLLAR - PUBLICACIONES SEM...,CO,No Definido,Sin Descripcion,Sin Descripcion,Mujer,0,0,0,19635000,0,0,702259557,701874067,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,20 Dia(s),Banco de Bogotá,Ahorros,223384926,No,Monica Patricia Botero Montoya,Cédula de Ciudadanía,42155861,GUILLERMO CASTAÑEDA SANDOLVAL,Cédula de Ciudadanía,1088259836,No definido,No definido,No definido,No,No definido,Carrera 7 #17-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2023-12-22T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.3373288,CO1.PCCNTR.4103402,6741-2022,terminado,V1.80111701,PRESTAR LOS SERVICIOS PROFESIONALES PARA APOYA...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2022-10-07T00:00:00.000,2022-10-12T00:00:00.000,2022-12-31T00:00:00.000,A convenir,Cédula de Ciudadanía,1088272688,DEIBY OSPINA ARIAS,No,No,No,No,No,No,No,Distribuido,Inversión,7207200,0,0,7207200,0,0,0,7207200,8108100,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,Deiby Ospina Arias,CO,cra.4 No.4-13,Cédula de Ciudadanía,1088272688,Hombre,0,0,0,7207200,0,0,702259557,714934494,PRESTAR LOS SERVICIOS PROFESIONALES PARA APOYA...,80 Dia(s),DAVIVIENDA,Ahorros,488415118667,No,ANGELA MARIA RUBIO MEJIA,Cédula de Ciudadanía,42137679,CARLOS ALBERTO FLECHAS CESPEDES,Cédula de Ciudadanía,7226523,No definido,No definido,No definido,No,No definido,Carrera 7 #17-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2023-11-13T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Columnas de la Fuente 2:")
print(contratos.columns.tolist())

Columnas de la Fuente 2:
['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad', 'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada', 'proceso_de_compra', 'id_contrato', 'referencia_del_contrato', 'estado_contrato', 'codigo_de_categoria_principal', 'descripcion_del_proceso', 'tipo_de_contrato', 'modalidad_de_contratacion', 'justificacion_modalidad_de', 'fecha_de_firma', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato', 'condiciones_de_entrega', 'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado', 'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n', 'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion', 'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato', 'valor_de_pago_adelantado', 'valor_facturado', 'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado', 'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp', 'saldo_vigencia', 'espostconflicto', 'dias_adicionados', 'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso', 'nombre_representante_legal', 'nacionalidad_representante_legal', 'domicilio_representante_legal', 'tipo_de_identificaci_n_representante_legal', 'identificaci_n_representante_legal', 'g_nero_representante_legal', 'presupuesto_general_de_la_nacion_pgn', 'sistema_general_de_participaciones', 'sistema_general_de_regal_as', 'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_', 'recursos_de_credito', 'recursos_propios', 'codigo_entidad', 'codigo_proveedor', 'objeto_del_contrato', 'duraci_n_del_contrato', 'nombre_del_banco', 'tipo_de_cuenta', 'n_mero_de_cuenta', 'el_contrato_puede_ser_prorrogado', 'nombre_ordenador_del_gasto', 'tipo_de_documento_ordenador_del_gasto', 'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor', 'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor', 'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago', 'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo', 'descripcion_documentos_tipo', 'direcci_n_de_ejecuci_n_del_contrato', 'criterios_de_sostenibilidad_ambiental', 'requisitos_ambientales_en_las_especificaciones_t_cnicas', 'criterios_ambientales_en_la_evaluaci_n_de_las_ofertas', 'obligaciones_contractuales_o_poscontractuales_a_nivel_ambiental', 'uso_de_etiquetado_ecol_gico', 'obligaciones_posconsumo', 'ultima_actualizacion', 'fecha_de_notificaci_n_de_prorrogaci_n', 'fecha_inicio_liquidacion', 'fecha_fin_liquidacion', 'fecha_inicio_reversi_n', 'fecha_fin_reversi_n', 'fecha_inicio_obligaciones_posconsumo', 'fecha_fin_obligaciones_posconsumo']

In [ ]:
print("========== TAMAÑO DE LAS FUENTES ==========")

print("Fuente 1 - Procesos:")
print("Filas:", procesos.shape[0])
print("Columnas:", procesos.shape[1])

print("\nFuente 2 - Contratos:")
print("Filas:", contratos.shape[0])
print("Columnas:", contratos.shape[1])

========== TAMAÑO DE LAS FUENTES ==========
Fuente 1 - Procesos:
Filas: 50000
Columnas: 57

Fuente 2 - Contratos:
Filas: 50000
Columnas: 95

In [ ]:
procesos["id_del_proceso"] = (
    procesos["id_del_proceso"]
    .astype("string")
    .str.strip()
)

contratos["proceso_de_compra"] = (
    contratos["proceso_de_compra"]
    .astype("string")
    .str.strip()
)

print("Tipo en Fuente 1:", procesos["id_del_proceso"].dtype)
print("Tipo en Fuente 2:", contratos["proceso_de_compra"].dtype)

Tipo en Fuente 1: string
Tipo en Fuente 2: string

In [ ]:
ids_procesos = set(
    procesos["id_del_proceso"].dropna()
)

ids_contratos = set(
    contratos["proceso_de_compra"].dropna()
)

ids_comunes = ids_procesos.intersection(ids_contratos)

print("IDs únicos en Procesos:", len(ids_procesos))
print("IDs únicos en Contratos:", len(ids_contratos))
print("IDs que aparecen en ambas fuentes:", len(ids_comunes))

IDs únicos en Procesos: 46808
IDs únicos en Contratos: 47274
IDs que aparecen en ambas fuentes: 0

In [ ]:
print("Ejemplo de IDs de PROCESOS:")
print(procesos["id_del_proceso"].dropna().head(10).tolist())

print("\nEjemplo de IDs de CONTRATOS:")
print(contratos["proceso_de_compra"].dropna().head(10).tolist())

Ejemplo de IDs de PROCESOS:
['CO1.REQ.3293809', 'CO1.REQ.2659965', 'CO1.REQ.6615293', 'CO1.REQ.3542690', 'CO1.REQ.4732912', 'CO1.REQ.10616693', 'CO1.REQ.4925786', 'CO1.REQ.5938977', 'CO1.REQ.4650963', 'CO1.REQ.1377798']

Ejemplo de IDs de CONTRATOS:
['CO1.BDOS.4655229', 'CO1.BDOS.3692285', 'CO1.BDOS.4661383', 'CO1.BDOS.2404408', 'CO1.BDOS.3373288', 'CO1.BDOS.6142046', 'CO1.BDOS.9491089', 'CO1.BDOS.2337909', 'CO1.BDOS.744481', 'CO1.BDOS.3798734']

In [ ]:
print("Tipos:")
print("id_del_proceso:", procesos["id_del_proceso"].dtype)
print("proceso_de_compra:", contratos["proceso_de_compra"].dtype)

Tipos:
id_del_proceso: string
proceso_de_compra: string

In [ ]:
ejemplos_contratos = contratos["proceso_de_compra"].dropna().head(20)

for valor in ejemplos_contratos:
    existe = valor in set(procesos["id_del_proceso"].dropna())
    print(valor, "->", existe)

CO1.BDOS.4655229 -> False
CO1.BDOS.3692285 -> False
CO1.BDOS.4661383 -> False
CO1.BDOS.2404408 -> False
CO1.BDOS.3373288 -> False
CO1.BDOS.6142046 -> False
CO1.BDOS.9491089 -> False
CO1.BDOS.2337909 -> False
CO1.BDOS.744481 -> False
CO1.BDOS.3798734 -> False
CO1.BDOS.1879440 -> False
CO1.BDOS.7797356 -> False
CO1.BDOS.6274664 -> False
CO1.BDOS.4571118 -> False
CO1.BDOS.1660861 -> False
CO1.BDOS.3714525 -> False
CO1.BDOS.5908585 -> False
CO1.BDOS.7576754 -> False
CO1.BDOS.3876451 -> False
CO1.BDOS.5589345 -> False

In [ ]:
ids_portafolio = set(
    procesos["id_del_portafolio"].dropna().astype("string").str.strip()
)

ids_proceso_compra = set(
    contratos["proceso_de_compra"].dropna().astype("string").str.strip()
)

ids_comunes_portafolio = ids_portafolio.intersection(ids_proceso_compra)

print("IDs únicos en id_del_portafolio:", len(ids_portafolio))
print("IDs únicos en proceso_de_compra:", len(ids_proceso_compra))
print("IDs en común:", len(ids_comunes_portafolio))

IDs únicos en id_del_portafolio: 46380
IDs únicos en proceso_de_compra: 47274
IDs en común: 17675

In [ ]:
print("Ejemplos de coincidencias:")

for valor in list(ids_comunes_portafolio)[:10]:
    print(valor)

Ejemplos de coincidencias:
CO1.BDOS.6693588
CO1.BDOS.7238962
CO1.BDOS.10773835
CO1.BDOS.7109107
CO1.BDOS.2895513
CO1.BDOS.5232011
CO1.BDOS.3321786
CO1.BDOS.8327058
CO1.BDOS.10890431
CO1.BDOS.10243665

In [ ]:
print(
    contratos[
        contratos["proceso_de_compra"] == "CO1.BDOS.3207380"
    ][["proceso_de_compra", "id_contrato", "nombre_entidad"]].head()
)

Empty DataFrame
Columns: [proceso_de_compra, id_contrato, nombre_entidad]
Index: []

In [ ]:
filas_procesos_antes = len(procesos)
filas_contratos_antes = len(contratos)

print("Filas de Procesos antes del cruce:", filas_procesos_antes)
print("Filas de Contratos antes del cruce:", filas_contratos_antes)

Filas de Procesos antes del cruce: 50000
Filas de Contratos antes del cruce: 50000

In [ ]:
resultado = pd.merge(
    procesos,
    contratos,
    left_on="id_del_portafolio",
    right_on="proceso_de_compra",
    how="inner",
    suffixes=("_proceso", "_contrato")
)

print("========== RESULTADO DEL CRUCE ==========")
print("Filas después del merge:", resultado.shape[0])
print("Columnas después del merge:", resultado.shape[1])

resultado.head()

========== RESULTADO DEL CRUCE ==========
Filas después del merge: 22591
Columnas después del merge: 152

,entidad,nit_entidad_proceso,departamento_entidad,ciudad_entidad,ordenentidad,codigo_pci,id_del_proceso,referencia_del_proceso,ppi,id_del_portafolio,nombre_del_procedimiento,descripci_n_del_procedimiento,fase,fecha_de_publicacion_del,fecha_de_ultima_publicaci,fecha_de_publicacion_fase_3,precio_base,modalidad_de_contratacion_proceso,justificaci_n_modalidad_de,duracion,unidad_de_duracion,ciudad_de_la_unidad_de,nombre_de_la_unidad_de,proveedores_invitados,proveedores_con_invitacion,visualizaciones_del,proveedores_que_manifestaron,respuestas_al_procedimiento,respuestas_externas,conteo_de_respuestas_a_ofertas,proveedores_unicos_con,numero_de_lotes,estado_del_procedimiento,id_estado_del_procedimiento,adjudicado,id_adjudicacion,codigoproveedor,departamento_proveedor,ciudad_proveedor,valor_total_adjudicacion,nombre_del_adjudicador,nombre_del_proveedor,nit_del_proveedor_adjudicado,codigo_principal_de_categoria,estado_de_apertura_del_proceso,tipo_de_contrato_proceso,subtipo_de_contrato,categorias_adicionales,urlproceso_proceso,codigo_entidad_proceso,estado_resumen,fecha_de_publicacion_fase_2,fecha_de_recepcion_de,fecha_de_apertura_de_respuesta,fecha_de_apertura_efectiva,fecha_adjudicacion,fecha_de_publicacion,nombre_entidad,nit_entidad_contrato,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,id_contrato,referencia_del_contrato,estado_contrato,codigo_de_categoria_principal,descripcion_del_proceso,tipo_de_contrato_contrato,modalidad_de_contratacion_contrato,justificacion_modalidad_de,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,condiciones_de_entrega,tipodocproveedor,documento_proveedor,proveedor_adjudicado,es_grupo,es_pyme,habilita_pago_adelantado,liquidaci_n,obligaci_n_ambiental,obligaciones_postconsumo,reversion,origen_de_los_recursos,destino_gasto,valor_del_contrato,valor_de_pago_adelantado,valor_facturado,valor_pendiente_de_pago,valor_pagado,valor_amortizado,valor_pendiente_de,valor_pendiente_de_ejecucion,saldo_cdp,saldo_vigencia,espostconflicto,dias_adicionados,puntos_del_acuerdo,pilares_del_acuerdo,urlproceso_contrato,nombre_representante_legal,nacionalidad_representante_legal,domicilio_representante_legal,tipo_de_identificaci_n_representante_legal,identificaci_n_representante_legal,g_nero_representante_legal,presupuesto_general_de_la_nacion_pgn,sistema_general_de_participaciones,sistema_general_de_regal_as,recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_,recursos_de_credito,recursos_propios,codigo_entidad_contrato,codigo_proveedor,objeto_del_contrato,duraci_n_del_contrato,nombre_del_banco,tipo_de_cuenta,n_mero_de_cuenta,el_contrato_puede_ser_prorrogado,nombre_ordenador_del_gasto,tipo_de_documento_ordenador_del_gasto,n_mero_de_documento_ordenador_del_gasto,nombre_supervisor,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,direcci_n_de_ejecuci_n_del_contrato,criterios_de_sostenibilidad_ambiental,requisitos_ambientales_en_las_especificaciones_t_cnicas,criterios_ambientales_en_la_evaluaci_n_de_las_ofertas,obligaciones_contractuales_o_poscontractuales_a_nivel_ambiental,uso_de_etiquetado_ecol_gico,obligaciones_posconsumo,ultima_actualizacion,fecha_de_notificaci_n_de_prorrogaci_n,fecha_inicio_liquidacion,fecha_fin_liquidacion,fecha_inicio_reversi_n,fecha_fin_reversi_n,fecha_inicio_obligaciones_posconsumo,fecha_fin_obligaciones_posconsumo
0,GOBERNACIÓN DE RISARALDA**,891480085,Risaralda,Pereira,Territorial,Centralizada,CO1.REQ.4925786,SI-SAMC-14-2023,702280165,CO1.BDOS.4818026,ACTIVIDADES DE MANTENIMIENTO DEL BIEN DE INTER...,ACTIVIDADES DE MANTENIMIENTO DEL BIEN DE INTER...,Presentación de observaciones,2023-08-14T00:00:00.000,2023-08-14T00:00:00.000,NaN,400081342,Selección Abreviada de Menor Cuantía,Presupuesto menor al 10% de la Menor Cuantía,45,día(s),Pereira,SECRETARIA DE INFRAESTRUCTURA,0,0,98,0,0,0,0,0,0,Evaluación,60,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.81101500,Cerrado,Obra,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,702280165,Presentación de observaciones,2023-08-14T00:00:00.000,2023-09-08T00:00:00.000,2023-09-08T00:00:00.000,2023-09-08T00:00:00.000,NaN,NaN,GOBERNACIÓN DE RISARALDA**,891480085,Risaralda,Pereira,"Colombia, Risaralda, Pereira",Territorial,No aplica/No pertenece,Ejecutivo,Centralizada,CO1.BDOS.4818026,CO1.PCCNTR.5428644,CO1.PCCNTR.5428644,Modificado,UNSPECIFIED,ACTIVIDADES DE MANTENIMIENTO DEL BIEN DE INTER...,Obra,Selección Abreviada de Menor Cuantía,Presupuesto menor al 10% de la Menor Cuantía,2023-10-11T00:00:00.000,2023-11-21T00:00:00.000,2024-12-14T00:00:00.000,No Definido,NIT,900925709,INGENIERIA Y PROYECTOS SOSTENIBLES SAS,No,Si,Si,No,No,No,No,Distribuido,Inversión,436272918,130881875.4,0,436272918,0,0,130881875.4,436272918,400140327,0,No,351,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,PAOLA ANDREA BUITRAGO ESPINOSA,CO,cra 7 n 16-50 0ficina 1003,Cédula de Ciudadanía,42146122*,Hombre,0,0,0,436272918,0,0,702280165,704541341,ACTIVIDADES DE MANTENIMIENTO DEL BIEN DE INTER...,70 Dia(s),Banco de Bogota,Corriente,912018777,No,MONICA PAOLA SALDARRIAGA ESCOBAR,Cédula de Ciudadanía,43158057,No definido,No definido,No definido,No definido,No definido,No definido,No,No definido,CALLE 19 N°9-75 PALACIO NACIONAL PISO 7 PEREI...,No definido,No definido,No definido,No definido,No definido,No,2024-11-19T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.1377798,SMI-LP-099-2020 (Fase de Selección (Presentaci...,702259557,CO1.BDOS.1298792,CONSTRUCCIÓN Y MANTENIMIENTO DE VÍAS (Fase de ...,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,Fase de Selección (Presentación de ofertas),2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,4449770565,Licitación pública Obra Publica,No Defenido,4,Mes(es),Pereira,SECRETARIA DE INFRAESTRUCTURA,0,0,730,0,247,0,0,247,2,Seleccionado,70,Si,CO1.AWD.854801,705442358,No Definido,No Definido,2473376817,Daniela Robledo Giraldo,CONSORCIO PROINGE 1,No Definido,V1.72141000,Cerrado,Obra,No Definido,V172141100,{'url': 'https://community.secop.gov.co/Public...,702259557,Adjudicado,NaN,2020-08-05T00:00:00.000,2020-10-02T00:00:00.000,2020-10-05T00:00:00.000,2020-10-09T00:00:00.000,NaN,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.1298792,CO1.PCCNTR.1930806,5285-2020,En ejecución,V1.72141000,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,Obra,Licitación pública Obra Publica,Article30_1993,2020-10-22T00:00:00.000,2020-11-03T00:00:00.000,2021-07-01T00:00:00.000,A convenir,Cédula de Ciudadanía,75106064,CONSORCIO SANTA LUCIA 3,Si,Si,No Definido,No,No,No,No,Distribuido,Inversión,1682572293,0,0,1682572293,0,0,0,1682572293,4450399733,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,CARLOS EDUARDO HERNANDEZ VALENCIA,CO,No Definido,Sin Descripcion,Sin Descripcion,No Definido,0,0,0,1682572293,0,0,702259557,709887871,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,241 Dia(s),No definido,No Definido,No definido,Si,JUAN CARLOS RESTREPO RESTREPO,Cédula de Ciudadanía,10127569,MILTON HURTADO GARCIA,Cédula de Ciudadanía,10271356,No definido,No definido,No definido,No definido,No definido,Cr 7 No. 18-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2021-07-21T00:00:00.000,2020-05-01T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN
2,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.1377798,SMI-LP-099-2020 (Fase de Selección (Presentaci...,702259557,CO1.BDOS.1298792,CONSTRUCCIÓN Y MANTENIMIENTO DE VÍAS (Fase de ...,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,Fase de Selección (Presentación de ofertas),2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,4449770565,Licitación pública Obra Publica,No Defenido,4,Mes(es),Pereira,SECRETARIA DE INFRAESTRUCTURA,0,0,730,0,247,0,0,247,2,Seleccionado,70,Si,CO1.AWD.854801,705442358,No Definido,No Definido,2473376817,Daniela Robledo Giraldo,CONSORCIO PROINGE 1,No Definido,V1.72141000,Cerrado,Obra,No Definido,V172141100,{'url': 'https://community.secop.gov.co/Public...,702259557,Adjudicado,NaN,2020-08-05T00:00:00.000,2020-10-02T00:00:00.000,2020-10-05T00:00:00.000,2020-10-09T00:00:00.000,NaN,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.1298792,CO1.PCCNTR.1904406,5285-2020,terminado,V1.72141000,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,Obra,Licitación pública Obra Publica,Article30_1993,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-31T00:00:00.000,A convenir,Cédula de Ciudadanía,75106064,CONSORCIO SANTA LUCIA 3,Si,Si,No Definido,No,No,No,No,Distribuido,Inversión,1916484569,0,0,1916484569,0,0,0,1916484569,4450399733,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,CARLOS EDUARDO HERNANDEZ VALENCIA,CO,No Definido,Sin Descripcion,Sin Descripcion,No Definido,0,0,0,1916484569,0,0,702259557,709887871,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,120 Dia(s),No definido,No Definido,No definido,Si,JUAN CARLOS RESTREPO RESTREPO,Cédula de Ciudadanía,10127569,MILTON HURTADO GARCIA,Cédula de Ciudadanía,10271356,No definido,No definido,No definido,No definido,No definido,Cr 7 No. 18-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2020-10-22T00:00:00.000,2020-12-29T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN
3,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.1377798,SMI-LP-099-2020 (Fase de Selección (Presentaci...,702259557,CO1.BDOS.1298792,CONSTRUCCIÓN Y MANTENIMIENTO DE VÍAS (Fase de ...,CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O REPARACIÓN ...,Fase de Selección (Presentación de ofertas),2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,2020-07-14T00:00:00.000,4449770565,Licitación pública Obra Publica,No Defenido,4,Mes(es),Pereira,SECRETARIA DE INFRAESTRUCTURA,0,0,730,0,247,0,0,247,2,Seleccionado,70,Si,CO1.AWD.854801,705442358,No Definido,No Definido,2473376817,Daniela Robledo Giraldo,CONSORCIO PROINGE 1,No Definido,V1.72141000,Cerrado,Obra,No Definido,V172141100,{'url': 'https://community.secop.gov.co/Public...,702259557,Adjudicado,NaN,2020-08-05T00:00:00.000,2020-10-02T00:00:00.000,2020-10-05T00:00:00.000,2020-10-09T00:00:00.000,NaN,MUNICIPIO DE PEREIRA- OFICIAL,891480030,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.1298792,CO1.PCCNTR.1904503,5307-2020,terminado,V1.72141000,OBRAS DE CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O RE...,Obra,Licitación pública Obra Publica,Article30_1993,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-10T00:00:00.000,A convenir,No Definido,No Definido,CONSORCIO PROINGE 1,Si,No,No Definido,No,No,No,No,Distribuido,Inversión,2473376817,0,0,2473376817,0,0,0,2473376817,2533766869,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,DIEGO ALEJANDRO FERNANDEZ FLOREZ,CO,No Definido,Sin Descripcion,Sin Descripcion,No Definido,0,0,0,2473376817,0,0,702259557,705442358,OBRAS DE CONSTRUCCIÓN Y/O MANTENIMIENTO Y/O RE...,105 Dia(s),No definido,No Definido,No definido,Si,JUAN CARLOS RESTREPO RESTREPO,Cédula de Ciudadanía,10127569,MILTON HURTADO GARCIA,Cédula de Ciudadanía,10271356,No definido,No definido,No definido,No definido,No definido,Cr 7 No. 18-55\nPereira\nRisaralda\nCOLOMBIA,No definido,No definido,No definido,No definido,No definido,No,2020-10-22T00:00:00.000,2020-12-29T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN
4,PERSONERIA MUNICIPAL DE PEREIRA,8914800302,Risaralda,Pereira,Territorial,Descentralizada,CO1.REQ.3914347,PE-CD-21-2023,715194270,CO1.BDOS.3819090,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA APO...,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA APO...,Presentación de oferta,2023-01-23T00:00:00.000,2023-01-23T00:00:00.000,2023-01-23T00:00:00.000,14400000,Contratación directa,Servicios profesionales y apoyo a la gestión,4,Mes(es),Pereira,Gestión Contractual,0,0,0,0,0,0,0,0,0,Seleccionado,70,No,No Adjudicado,No Definido,No Definido,No Definido,0,No Adjudicado,No Definido,No Definido,V1.80111600,Abierto,Prestación de servicios,No Definido,No definido,{'url': 'https://community.secop.gov.co/Public...,715194270,Presentación de oferta,NaN,NaN,NaN,NaN,NaN,NaN,PERSONERIA MUNICIPAL DE PEREIRA,8914800302,Risaralda,Pereira,"Colombia, Risaralda , Pereira",Territorial,No aplica/No pertenece,Corporación Autónoma,Descentralizada,CO1.BDOS.3819090,CO1.PCCNTR.4459047,21-2023,terminado,V1.80111600,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA APO...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión,2023-01-26T00:00:00.000,2023-02-01T00:00:00.000,2023-05-31T00:00:00.000,A convenir,Cédula de Ciudadanía,1088318599,MATEO LOPEZ CHICA,No,No,No,No,No,No,No,Distribuido,Funcionamiento,14400000,0,0,14400000,0,0,0,14400000,14400000,0,No,0,No aplica,No aplica,{'url': 'https://community.secop.gov.co/Public...,MATEO LOPEZ CHICA,CO,Mz L Casa 25 Barrio El Cardal,Cédula de Ciudadanía,1088318599,No Definido,0,0,0,14400000,0,0,715194270,708917117,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA APO...,4 Mes(es),No definido,No Definido,No definido,Si,JUAN FERNANDO LÓPEZ CORZO,Cédula de Ciudadanía,10014828,JOHAN SEBASTIAN VILLALBA HERNANDEZ,Cédula de Ciudadanía,1225088367,No definido,No definido,No definido,No,No definido,Cll 25 n 7-48 piso 3 y 4 Unidad Administrativa...,No definido,No definido,No definido,No definido,No definido,No,2023-05-25T00:00:00.000,2023-05-23T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
print("Filas Fuente 1 antes:", filas_procesos_antes)
print("Filas Fuente 2 antes:", filas_contratos_antes)
print("Filas después del merge:", len(resultado))

Filas Fuente 1 antes: 50000
Filas Fuente 2 antes: 50000
Filas después del merge: 22591

### Cruce de las fuentes

Las dos fuentes de SECOP II serán integradas utilizando como relación principal el identificador del proceso de compra. En la fuente *SECOP II – Procesos de Contratación* se utilizará la columna id_del_portafolio, mientras que en *SECOP II – Contratos Electrónicos* se utilizará la columna proceso_de_compra.

Durante la etapa de adquisición se verificó la correspondencia entre estos identificadores, encontrando 16.767 identificadores únicos en común. El cruce se realizará mediante un inner merge, conservando los registros que presenten correspondencia entre ambas fuentes.

Como resultado de la prueba realizada con los datos adquiridos, el cruce produjo 21.792 registros.

Antes del cruce se tenían 50.000 registros de cada fuente y después del cruce se obtuvieron 21.792 registros relacionados.

In [ ]:
procesos_limpios = procesos[
    [
        "id_del_proceso",
        "id_del_portafolio",
        "entidad",
        "departamento_entidad",
        "ciudad_entidad",
        "fecha_de_publicacion_del",
        "modalidad_de_contratacion",
        "tipo_de_contrato",
        "precio_base",
        "valor_total_adjudicacion",
        "estado_del_procedimiento"
    ]
].copy()

In [ ]:
contratos_limpios = contratos[
    [
        "proceso_de_compra",
        "id_contrato",
        "nombre_entidad",
        "fecha_de_firma",
        "fecha_de_inicio_del_contrato",
        "fecha_de_fin_del_contrato",
        "modalidad_de_contratacion",
        "tipo_de_contrato",
        "proveedor_adjudicado",
        "valor_del_contrato",
        "estado_contrato"
    ]
].copy()

In [ ]:
dataset_final = pd.merge(
    procesos_limpios,
    contratos_limpios,
    left_on="id_del_portafolio",
    right_on="proceso_de_compra",
    how="inner",
    suffixes=("_proceso", "_contrato")
)

print("========== DATASET FINAL ==========")
print("Filas:", dataset_final.shape[0])
print("Columnas:", dataset_final.shape[1])

dataset_final.head()

========== DATASET FINAL ==========
Filas: 22591
Columnas: 22

,id_del_proceso,id_del_portafolio,entidad,departamento_entidad,ciudad_entidad,fecha_de_publicacion_del,modalidad_de_contratacion_proceso,tipo_de_contrato_proceso,precio_base,valor_total_adjudicacion,estado_del_procedimiento,proceso_de_compra,id_contrato,nombre_entidad,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,modalidad_de_contratacion_contrato,tipo_de_contrato_contrato,proveedor_adjudicado,valor_del_contrato,estado_contrato
0,CO1.REQ.4925786,CO1.BDOS.4818026,GOBERNACIÓN DE RISARALDA**,Risaralda,Pereira,2023-08-14T00:00:00.000,Selección Abreviada de Menor Cuantía,Obra,400081342,0,Evaluación,CO1.BDOS.4818026,CO1.PCCNTR.5428644,GOBERNACIÓN DE RISARALDA**,2023-10-11T00:00:00.000,2023-11-21T00:00:00.000,2024-12-14T00:00:00.000,Selección Abreviada de Menor Cuantía,Obra,INGENIERIA Y PROYECTOS SOSTENIBLES SAS,436272918,Modificado
1,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1930806,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-22T00:00:00.000,2020-11-03T00:00:00.000,2021-07-01T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO SANTA LUCIA 3,1682572293,En ejecución
2,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1904406,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-31T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO SANTA LUCIA 3,1916484569,terminado
3,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1904503,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-10T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO PROINGE 1,2473376817,terminado
4,CO1.REQ.3914347,CO1.BDOS.3819090,PERSONERIA MUNICIPAL DE PEREIRA,Risaralda,Pereira,2023-01-23T00:00:00.000,Contratación directa,Prestación de servicios,14400000,0,Seleccionado,CO1.BDOS.3819090,CO1.PCCNTR.4459047,PERSONERIA MUNICIPAL DE PEREIRA,2023-01-26T00:00:00.000,2023-02-01T00:00:00.000,2023-05-31T00:00:00.000,Contratación directa,Prestación de servicios,MATEO LOPEZ CHICA,14400000,terminado

In [ ]:
print(dataset_final.columns.tolist())

['id_del_proceso', 'id_del_portafolio', 'entidad', 'departamento_entidad', 'ciudad_entidad', 'fecha_de_publicacion_del', 'modalidad_de_contratacion_proceso', 'tipo_de_contrato_proceso', 'precio_base', 'valor_total_adjudicacion', 'estado_del_procedimiento', 'proceso_de_compra', 'id_contrato', 'nombre_entidad', 'fecha_de_firma', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato', 'modalidad_de_contratacion_contrato', 'tipo_de_contrato_contrato', 'proveedor_adjudicado', 'valor_del_contrato', 'estado_contrato']

In [ ]:
print(dataset_final.dtypes)

id_del_proceso                        string[python]
id_del_portafolio                             object
entidad                                       object
departamento_entidad                          object
ciudad_entidad                                object
fecha_de_publicacion_del                      object
modalidad_de_contratacion_proceso             object
tipo_de_contrato_proceso                      object
precio_base                                   object
valor_total_adjudicacion                      object
estado_del_procedimiento                      object
proceso_de_compra                     string[python]
id_contrato                                   object
nombre_entidad                                object
fecha_de_firma                                object
fecha_de_inicio_del_contrato                  object
fecha_de_fin_del_contrato                     object
modalidad_de_contratacion_contrato            object
tipo_de_contrato_contrato                     object
proveedor_adjudicado                          object
valor_del_contrato                            object
estado_contrato                               object
dtype: object

In [ ]:
print(dataset_final.isna().sum())

id_del_proceso                          0
id_del_portafolio                       0
entidad                                 0
departamento_entidad                    0
ciudad_entidad                          0
fecha_de_publicacion_del               87
modalidad_de_contratacion_proceso       0
tipo_de_contrato_proceso                0
precio_base                             0
valor_total_adjudicacion                0
estado_del_procedimiento                0
proceso_de_compra                       0
id_contrato                             0
nombre_entidad                          0
fecha_de_firma                        239
fecha_de_inicio_del_contrato          686
fecha_de_fin_del_contrato               0
modalidad_de_contratacion_contrato      0
tipo_de_contrato_contrato               0
proveedor_adjudicado                    0
valor_del_contrato                      0
estado_contrato                         0
dtype: int64

## Revisión inicial de calidad de los datos

Después de realizar el cruce de las fuentes se revisaron los tipos de datos y los valores faltantes del dataset resultante.

El dataset cruzado contiene 21.792 registros y 22 columnas.

La mayoría de las columnas no presentan valores faltantes. Sin embargo, se identificaron valores faltantes principalmente en las variables relacionadas con las fechas de los contratos:

* `fecha_de_publicacion_del`: 78 valores faltantes.
* `fecha_de_firma`: 1.741 valores faltantes.
* `fecha_de_inicio_del_contrato`: 2.148 valores faltantes.
* `fecha_de_fin_del_contrato`: 287 valores faltantes.

Estos valores faltantes se conservarán en esta etapa de adquisición y serán considerados posteriormente durante la preparación y el análisis de los datos. No se eliminarán automáticamente porque la ausencia de una fecha puede corresponder a diferentes estados o situaciones del registro y debe analizarse antes de decidir cómo tratarla.

In [ ]:
diccionario_datos = pd.DataFrame([
    {
        "columna": "id_del_proceso",
        "tipo_de_dato": "string[python]",
        "significado": "Identificador del proceso de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "id_del_portafolio",
        "tipo_de_dato": "object",
        "significado": "Identificador del portafolio asociado al proceso y utilizado como llave para relacionar las dos fuentes.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "entidad",
        "tipo_de_dato": "object",
        "significado": "Nombre de la entidad que publica el proceso de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "departamento_entidad",
        "tipo_de_dato": "object",
        "significado": "Departamento donde está registrada la entidad contratante.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "ciudad_entidad",
        "tipo_de_dato": "object",
        "significado": "Ciudad donde está registrada la entidad contratante.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "fecha_de_publicacion_del",
        "tipo_de_dato": "object",
        "significado": "Fecha de publicación del proceso de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "modalidad_de_contratacion_proceso",
        "tipo_de_dato": "object",
        "significado": "Modalidad mediante la cual se desarrolla el proceso de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "tipo_de_contrato_proceso",
        "tipo_de_dato": "object",
        "significado": "Tipo de contrato registrado en el proceso.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "precio_base",
        "tipo_de_dato": "object",
        "significado": "Valor base registrado para el proceso de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "valor_total_adjudicacion",
        "tipo_de_dato": "object",
        "significado": "Valor total adjudicado asociado al proceso.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "estado_del_procedimiento",
        "tipo_de_dato": "object",
        "significado": "Estado registrado del procedimiento de contratación.",
        "fuente": "SECOP II - Procesos de Contratación"
    },
    {
        "columna": "proceso_de_compra",
        "tipo_de_dato": "string[python]",
        "significado": "Identificador del proceso de compra asociado al contrato. Se utiliza como contraparte de la llave de cruce.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "id_contrato",
        "tipo_de_dato": "object",
        "significado": "Identificador del contrato electrónico.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "nombre_entidad",
        "tipo_de_dato": "object",
        "significado": "Nombre de la entidad asociada al contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "fecha_de_firma",
        "tipo_de_dato": "object",
        "significado": "Fecha registrada de firma del contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "fecha_de_inicio_del_contrato",
        "tipo_de_dato": "object",
        "significado": "Fecha registrada de inicio del contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "fecha_de_fin_del_contrato",
        "tipo_de_dato": "object",
        "significado": "Fecha registrada de finalización del contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "modalidad_de_contratacion_contrato",
        "tipo_de_dato": "object",
        "significado": "Modalidad de contratación registrada en el contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "tipo_de_contrato_contrato",
        "tipo_de_dato": "object",
        "significado": "Tipo de contrato registrado en la fuente de contratos.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "proveedor_adjudicado",
        "tipo_de_dato": "object",
        "significado": "Proveedor al que fue adjudicado el contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "valor_del_contrato",
        "tipo_de_dato": "object",
        "significado": "Valor registrado del contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    },
    {
        "columna": "estado_contrato",
        "tipo_de_dato": "object",
        "significado": "Estado registrado del contrato.",
        "fuente": "SECOP II - Contratos Electrónicos"
    }
])

diccionario_datos

,columna,tipo_de_dato,significado,fuente
0,id_del_proceso,string[python],Identificador del proceso de contratación.,SECOP II - Procesos de Contratación
1,id_del_portafolio,object,Identificador del portafolio asociado al proce...,SECOP II - Procesos de Contratación
2,entidad,object,Nombre de la entidad que publica el proceso de...,SECOP II - Procesos de Contratación
3,departamento_entidad,object,Departamento donde está registrada la entidad ...,SECOP II - Procesos de Contratación
4,ciudad_entidad,object,Ciudad donde está registrada la entidad contra...,SECOP II - Procesos de Contratación
5,fecha_de_publicacion_del,object,Fecha de publicación del proceso de contratación.,SECOP II - Procesos de Contratación
6,modalidad_de_contratacion_proceso,object,Modalidad mediante la cual se desarrolla el pr...,SECOP II - Procesos de Contratación
7,tipo_de_contrato_proceso,object,Tipo de contrato registrado en el proceso.,SECOP II - Procesos de Contratación
8,precio_base,object,Valor base registrado para el proceso de contr...,SECOP II - Procesos de Contratación
9,valor_total_adjudicacion,object,Valor total adjudicado asociado al proceso.,SECOP II - Procesos de Contratación
10,estado_del_procedimiento,object,Estado registrado del procedimiento de contrat...,SECOP II - Procesos de Contratación
11,proceso_de_compra,string[python],Identificador del proceso de compra asociado a...,SECOP II - Contratos Electrónicos
12,id_contrato,object,Identificador del contrato electrónico.,SECOP II - Contratos Electrónicos
13,nombre_entidad,object,Nombre de la entidad asociada al contrato.,SECOP II - Contratos Electrónicos
14,fecha_de_firma,object,Fecha registrada de firma del contrato.,SECOP II - Contratos Electrónicos
15,fecha_de_inicio_del_contrato,object,Fecha registrada de inicio del contrato.,SECOP II - Contratos Electrónicos
16,fecha_de_fin_del_contrato,object,Fecha registrada de finalización del contrato.,SECOP II - Contratos Electrónicos
17,modalidad_de_contratacion_contrato,object,Modalidad de contratación registrada en el con...,SECOP II - Contratos Electrónicos
18,tipo_de_contrato_contrato,object,Tipo de contrato registrado en la fuente de co...,SECOP II - Contratos Electrónicos
19,proveedor_adjudicado,object,Proveedor al que fue adjudicado el contrato.,SECOP II - Contratos Electrónicos
20,valor_del_contrato,object,Valor registrado del contrato.,SECOP II - Contratos Electrónicos
21,estado_contrato,object,Estado registrado del contrato.,SECOP II - Contratos Electrónicos

In [ ]:
print("Columnas del dataset final:", len(dataset_final.columns))
print("Filas del dataset final:", len(dataset_final))

print("Columnas documentadas:", len(diccionario_datos))

if set(dataset_final.columns) == set(diccionario_datos["columna"]):
    print("✓ Todas las columnas del dataset final están documentadas.")
else:
    print(" Hay columnas que faltan o sobran en el diccionario.")

Columnas del dataset final: 22
Filas del dataset final: 22591
Columnas documentadas: 22
✓ Todas las columnas del dataset final están documentadas.

In [ ]:
diccionario_datos.to_csv(
    "diccionario_datos_secop_pereira.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✓ Diccionario guardado correctamente.")

✓ Diccionario guardado correctamente.

In [ ]:
dataset_final.to_csv(
    "dataset_secop_pereira_cruzado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✓ Dataset cruzado guardado correctamente.")

✓ Dataset cruzado guardado correctamente.

In [ ]:
import os
from google.colab import files
print("Archivos CSV encontrados:")
csvs = [f for f in os.listdir('.') if f.endswith('.csv')]
print(csvs)

if "diccionario_datos_secop_pereira.csv" in csvs:
    files.download("diccionario_datos_secop_pereira.csv")
else:
    print("El archivo 'diccionario_datos_secop_pereira.csv' no existe aún.")

if "dataset_secop_pereira_cruzado.csv" in csvs:
    files.download("dataset_secop_pereira_cruzado.csv")
else:
    print("El archivo 'dataset_secop_pereira_cruzado.csv' no existe aún.")

Archivos CSV encontrados:
['dataset_secop_pereira_cruzado.csv', 'diccionario_datos_secop_pereira.csv']

In [ ]:
print("Tamaño del dataset:", dataset_final.shape)

display(dataset_final.dtypes)

display(dataset_final.head())

Tamaño del dataset: (22591, 22)

id_del_proceso                        string[python]
id_del_portafolio                             object
entidad                                       object
departamento_entidad                          object
ciudad_entidad                                object
fecha_de_publicacion_del                      object
modalidad_de_contratacion_proceso             object
tipo_de_contrato_proceso                      object
precio_base                                   object
valor_total_adjudicacion                      object
estado_del_procedimiento                      object
proceso_de_compra                     string[python]
id_contrato                                   object
nombre_entidad                                object
fecha_de_firma                                object
fecha_de_inicio_del_contrato                  object
fecha_de_fin_del_contrato                     object
modalidad_de_contratacion_contrato            object
tipo_de_contrato_contrato                     object
proveedor_adjudicado                          object
valor_del_contrato                            object
estado_contrato                               object
dtype: object

,id_del_proceso,id_del_portafolio,entidad,departamento_entidad,ciudad_entidad,fecha_de_publicacion_del,modalidad_de_contratacion_proceso,tipo_de_contrato_proceso,precio_base,valor_total_adjudicacion,estado_del_procedimiento,proceso_de_compra,id_contrato,nombre_entidad,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,modalidad_de_contratacion_contrato,tipo_de_contrato_contrato,proveedor_adjudicado,valor_del_contrato,estado_contrato
0,CO1.REQ.4925786,CO1.BDOS.4818026,GOBERNACIÓN DE RISARALDA**,Risaralda,Pereira,2023-08-14T00:00:00.000,Selección Abreviada de Menor Cuantía,Obra,400081342,0,Evaluación,CO1.BDOS.4818026,CO1.PCCNTR.5428644,GOBERNACIÓN DE RISARALDA**,2023-10-11T00:00:00.000,2023-11-21T00:00:00.000,2024-12-14T00:00:00.000,Selección Abreviada de Menor Cuantía,Obra,INGENIERIA Y PROYECTOS SOSTENIBLES SAS,436272918,Modificado
1,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1930806,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-22T00:00:00.000,2020-11-03T00:00:00.000,2021-07-01T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO SANTA LUCIA 3,1682572293,En ejecución
2,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1904406,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-31T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO SANTA LUCIA 3,1916484569,terminado
3,CO1.REQ.1377798,CO1.BDOS.1298792,MUNICIPIO DE PEREIRA- OFICIAL,Risaralda,Pereira,2020-07-14T00:00:00.000,Licitación pública Obra Publica,Obra,4449770565,2473376817,Seleccionado,CO1.BDOS.1298792,CO1.PCCNTR.1904503,MUNICIPIO DE PEREIRA- OFICIAL,2020-10-21T00:00:00.000,2020-10-22T00:00:00.000,2020-12-10T00:00:00.000,Licitación pública Obra Publica,Obra,CONSORCIO PROINGE 1,2473376817,terminado
4,CO1.REQ.3914347,CO1.BDOS.3819090,PERSONERIA MUNICIPAL DE PEREIRA,Risaralda,Pereira,2023-01-23T00:00:00.000,Contratación directa,Prestación de servicios,14400000,0,Seleccionado,CO1.BDOS.3819090,CO1.PCCNTR.4459047,PERSONERIA MUNICIPAL DE PEREIRA,2023-01-26T00:00:00.000,2023-02-01T00:00:00.000,2023-05-31T00:00:00.000,Contratación directa,Prestación de servicios,MATEO LOPEZ CHICA,14400000,terminado

In [ ]:
%whos

Variable                 Type         Data/Info
-----------------------------------------------
StringIO                 type         <class '_io.StringIO'>
URL_CONTRATOS            str          https://www.datos.gov.co/resource/jbjy-vk9h.json
URL_PROCESOS             str          https://www.datos.gov.co/resource/p6dx-8zbt.json
contratos                DataFrame                          nom<...>[50000 rows x 95 columns]
contratos_limpios        DataFrame          proceso_de_compra  <...>[50000 rows x 11 columns]
csvs                     list         n=2
dataset_final            DataFrame            id_del_proceso id<...>[22591 rows x 22 columns]
diccionario_datos        DataFrame                             <...> Contratos Electrónicos
drive                    module       <module 'google.colab.dri<...>s/google/colab/drive.py'>
ejemplos_contratos       Series       0     CO1.BDOS.4655229\n1<...>_de_compra, dtype: string
existe                   bool         False
filas_contratos_antes    int          50000
filas_procesos_antes     int          50000
files                    module       <module 'google.colab.fil<...>s/google/colab/files.py'>
ids_comunes              set          set()
ids_comunes_portafolio   set          {'CO1.BDOS.6693588', 'CO1<...>864', 'CO1.BDOS.2629214'}
ids_contratos            set          {'CO1.BDOS.6693588', 'CO1<...>272', 'CO1.BDOS.9435988'}
ids_portafolio           set          {'CO1.BDOS.6693588', 'CO1<...>755', 'CO1.BDOS.4671304'}
ids_proceso_compra       set          {'CO1.BDOS.6693588', 'CO1<...>272', 'CO1.BDOS.9435988'}
ids_procesos             set          {'CO1.REQ.9743019', 'CO1.<...>8452', 'CO1.REQ.9813353'}
os                       module       <module 'os' (frozen)>
params_contratos         dict         n=2
params_procesos          dict         n=2
pd                       module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
procesos                 DataFrame                             <...>[50000 rows x 57 columns]
procesos_limpios         DataFrame             id_del_proceso i<...>[50000 rows x 11 columns]
requests                 module       <module 'requests' from '<...>es/requests/__init__.py'>
respuesta                Response     <Response [200]>
respuesta_contratos      Response     <Response [200]>
resultado                DataFrame                             <...>22591 rows x 152 columns]
valor                    str          CO1.BDOS.10243665

In [ ]:
print("Tamaño del dataset:", dataset_final.shape)

print("\nTipos de datos:")
display(dataset_final.dtypes)

print("\nValores faltantes:")
display(dataset_final.isnull().sum())

Tamaño del dataset: (22591, 22)

Tipos de datos:

id_del_proceso                        string[python]
id_del_portafolio                             object
entidad                                       object
departamento_entidad                          object
ciudad_entidad                                object
fecha_de_publicacion_del                      object
modalidad_de_contratacion_proceso             object
tipo_de_contrato_proceso                      object
precio_base                                   object
valor_total_adjudicacion                      object
estado_del_procedimiento                      object
proceso_de_compra                     string[python]
id_contrato                                   object
nombre_entidad                                object
fecha_de_firma                                object
fecha_de_inicio_del_contrato                  object
fecha_de_fin_del_contrato                     object
modalidad_de_contratacion_contrato            object
tipo_de_contrato_contrato                     object
proveedor_adjudicado                          object
valor_del_contrato                            object
estado_contrato                               object
dtype: object

Valores faltantes:

id_del_proceso                          0
id_del_portafolio                       0
entidad                                 0
departamento_entidad                    0
ciudad_entidad                          0
fecha_de_publicacion_del               87
modalidad_de_contratacion_proceso       0
tipo_de_contrato_proceso                0
precio_base                             0
valor_total_adjudicacion                0
estado_del_procedimiento                0
proceso_de_compra                       0
id_contrato                             0
nombre_entidad                          0
fecha_de_firma                        239
fecha_de_inicio_del_contrato          686
fecha_de_fin_del_contrato               0
modalidad_de_contratacion_contrato      0
tipo_de_contrato_contrato               0
proveedor_adjudicado                    0
valor_del_contrato                      0
estado_contrato                         0
dtype: int64

# Calidad de datos
 En esta etapa se revisan los tipos de datos, los valores faltantes y las posibles inconsistencias del dataset integrado de contratación pública. Se busca mejorar la calidad de la información antes de realizar el análisis exploratorio, conservando los registros originales siempre que sea posible.

In [ ]:
import pandas as pd

columnas_fecha = [
    "fecha_de_publicacion_del",
    "fecha_de_firma",
    "fecha_de_inicio_del_contrato",
    "fecha_de_fin_del_contrato"
]

for columna in columnas_fecha:
    dataset_final[columna] = pd.to_datetime(
        dataset_final[columna],
        errors="coerce"
    )

print("Tipos de datos después de convertir las fechas:")
display(dataset_final[columnas_fecha].dtypes)

print("Valores faltantes después de convertir las fechas:")
display(dataset_final[columnas_fecha].isnull().sum())

Tipos de datos después de convertir las fechas:

fecha_de_publicacion_del        datetime64[ns]
fecha_de_firma                  datetime64[ns]
fecha_de_inicio_del_contrato    datetime64[ns]
fecha_de_fin_del_contrato       datetime64[ns]
dtype: object

Valores faltantes después de convertir las fechas:

fecha_de_publicacion_del         87
fecha_de_firma                  239
fecha_de_inicio_del_contrato    686
fecha_de_fin_del_contrato         0
dtype: int64

In [ ]:
fechas_invertidas = dataset_final[
    dataset_final["fecha_de_fin_del_contrato"]
    < dataset_final["fecha_de_inicio_del_contrato"]
]

print("Contratos con fechas invertidas:", len(fechas_invertidas))

display(
    fechas_invertidas[
        [
            "id_contrato",
            "fecha_de_inicio_del_contrato",
            "fecha_de_fin_del_contrato"
        ]
    ].head(20)
)

Contratos con fechas invertidas: 2

,id_contrato,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato
3065,CO1.PCCNTR.8539178,2025-11-26,2025-10-31
13166,CO1.PCCNTR.8596304,2025-11-24,2025-11-18

# Inconsistencia 1: Fechas de inicio y finalización invertidas

Durante la revisión de calidad de datos se identificaron 2 contratos cuyas fechas de finalización son anteriores a las fechas de inicio.

ID del contrato          Fecha de inicio       Fecha de finalización

CO1.PCCNTR.8539178         26/11/2025            31/10/2025

CO1.PCCNTR.8596304         24/11/2025            18/11/2025

Tratamiento: los registros se conservarán y se marcarán para verificación, ya que no contamos con información suficiente para determinar cuál de las fechas es correcta. No se modificarán fechas sin consultar la fuente original.

Justificación: una fecha de finalización anterior a la fecha de inicio constituye una inconsistencia temporal que puede afectar el análisis de la duración de los contratos. Por ello, se debe verificar la información antes de corregirla o excluirla.

In [ ]:
dataset_final["fecha_invertida"] = (
    dataset_final["fecha_de_fin_del_contrato"]
    < dataset_final["fecha_de_inicio_del_contrato"]
)

print("Contratos marcados para revisión:")
display(
    dataset_final.loc[
        dataset_final["fecha_invertida"],
        [
            "id_contrato",
            "fecha_de_inicio_del_contrato",
            "fecha_de_fin_del_contrato",
            "fecha_invertida"
        ]
    ]
)

Contratos marcados para revisión:

,id_contrato,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,fecha_invertida
3065,CO1.PCCNTR.8539178,2025-11-26,2025-10-31,True
13166,CO1.PCCNTR.8596304,2025-11-24,2025-11-18,True

In [ ]:
columnas_valor = [
    "precio_base",
    "valor_total_adjudicacion",
    "valor_del_contrato"
]

for columna in columnas_valor:
    print(f"\n--- {columna} ---")
    print("Tipo de dato:", dataset_final[columna].dtype)
    display(dataset_final[columna].head(10).tolist())

--- precio_base ---
Tipo de dato: object

['400081342',
 '4449770565',
 '4449770565',
 '4449770565',
 '14400000',
 '5034898',
 '21000000',
 '643074984',
 '643074984',
 '643074984']

--- valor_total_adjudicacion ---
Tipo de dato: object

['0',
 '2473376817',
 '2473376817',
 '2473376817',
 '0',
 '0',
 '0',
 '34650000',
 '34650000',
 '34650000']

--- valor_del_contrato ---
Tipo de dato: object

['436272918',
 '1682572293',
 '1916484569',
 '2473376817',
 '14400000',
 '6125793',
 '30000000',
 '17014635',
 '440853769',
 '34650000']

In [ ]:
columnas_valor = [
    "precio_base",
    "valor_total_adjudicacion",
    "valor_del_contrato"
]

for columna in columnas_valor:
    dataset_final[columna] = pd.to_numeric(
        dataset_final[columna],
        errors="coerce"
    )

print("Tipos de datos después de la conversión:")
display(dataset_final[columnas_valor].dtypes)

print("Resumen estadístico de los importes:")
display(dataset_final[columnas_valor].describe())

Tipos de datos después de la conversión:

precio_base                   int64
valor_total_adjudicacion      int64
valor_del_contrato          float64
dtype: object

Resumen estadístico de los importes:

        precio_base  valor_total_adjudicacion  valor_del_contrato
count  2.259100e+04              2.259100e+04        2.259100e+04
mean   5.078395e+08              1.109272e+08        2.533515e+08
std    4.829360e+09              9.541008e+08        2.139104e+09
min    0.000000e+00              0.000000e+00        0.000000e+00
25%    1.140000e+07              0.000000e+00        1.097333e+07
50%    2.100000e+07              0.000000e+00        2.016220e+07
75%    5.373515e+07              0.000000e+00        3.740085e+07
max    5.999713e+11              5.419763e+10        2.403800e+11

In [ ]:
for columna in columnas_valor:
    negativos = dataset_final[dataset_final[columna] < 0]

    print(f"{columna}: {len(negativos)} valores negativos")

precio_base: 0 valores negativos
valor_total_adjudicacion: 0 valores negativos
valor_del_contrato: 0 valores negativos

In [ ]:
ceros_adjudicacion = dataset_final[
    dataset_final["valor_total_adjudicacion"] == 0
]

print("Total de registros con adjudicación en cero:",
      len(ceros_adjudicacion))

print("\nEstados de los procedimientos:")
display(
    ceros_adjudicacion["estado_del_procedimiento"]
    .value_counts(dropna=False)
)

print("\nComparación de importes:")
display(
    ceros_adjudicacion[
        [
            "estado_del_procedimiento",
            "valor_total_adjudicacion",
            "valor_del_contrato",
            "estado_contrato"
        ]
    ].head(20)
)

Total de registros con adjudicación en cero: 18426

Estados de los procedimientos:

estado_del_procedimiento
Seleccionado     17779
Evaluación         610
Cancelado           27
Publicado            4
En aprobación        4
Aprobado             2
Name: count, dtype: int64

Comparación de importes:

,estado_del_procedimiento,valor_total_adjudicacion,valor_del_contrato,estado_contrato
0,Evaluación,0,436272918.0,Modificado
4,Seleccionado,0,14400000.0,terminado
5,Seleccionado,0,6125793.0,En ejecución
6,Seleccionado,0,30000000.0,Modificado
23,Seleccionado,0,21301000.0,Cerrado
24,Seleccionado,0,31500000.0,terminado
25,Seleccionado,0,13800000.0,Cerrado
31,Seleccionado,0,21600000.0,Cerrado
32,Seleccionado,0,18300000.0,Cerrado
40,Seleccionado,0,21596904.0,Cerrado
41,Seleccionado,0,2979000.0,Cerrado
42,Seleccionado,0,16216200.0,Cerrado
43,Seleccionado,0,10800000.0,En ejecución
44,Seleccionado,0,27007865.0,Aprobado
45,Seleccionado,0,22376667.0,Modificado
46,Seleccionado,0,14000000.0,En ejecución
47,Seleccionado,0,18666666.0,En ejecución
48,Seleccionado,0,24403588.0,En ejecución
49,Seleccionado,0,16200000.0,enviado Proveedor
50,Seleccionado,0,16682400.0,Cerrado

In [ ]:
casos_revision = dataset_final[
    (dataset_final["valor_total_adjudicacion"] == 0) &
    (dataset_final["valor_del_contrato"] > 0)
]

print(
    "Registros con adjudicación en cero y contrato positivo:",
    len(casos_revision)
)

print(
    "Porcentaje sobre el dataset:",
    round(len(casos_revision) / len(dataset_final) * 100, 2),
    "%"
)

display(
    casos_revision[
        [
            "id_del_proceso",
            "id_del_portafolio",
            "estado_del_procedimiento",
            "valor_total_adjudicacion",
            "id_contrato",
            "valor_del_contrato",
            "estado_contrato"
        ]
    ].head(15)
)

Registros con adjudicación en cero y contrato positivo: 18330
Porcentaje sobre el dataset: 81.14 %

,id_del_proceso,id_del_portafolio,estado_del_procedimiento,valor_total_adjudicacion,id_contrato,valor_del_contrato,estado_contrato
0,CO1.REQ.4925786,CO1.BDOS.4818026,Evaluación,0,CO1.PCCNTR.5428644,436272918.0,Modificado
4,CO1.REQ.3914347,CO1.BDOS.3819090,Seleccionado,0,CO1.PCCNTR.4459047,14400000.0,terminado
5,CO1.REQ.6957752,CO1.BDOS.6827987,Seleccionado,0,CO1.PCCNTR.6867266,6125793.0,En ejecución
6,CO1.REQ.9985108,CO1.BDOS.9816506,Seleccionado,0,CO1.PCCNTR.9204373,30000000.0,Modificado
23,CO1.REQ.3956970,CO1.BDOS.3861909,Seleccionado,0,CO1.PCCNTR.4499020,21301000.0,Cerrado
24,CO1.REQ.9599017,CO1.BDOS.9430785,Seleccionado,0,CO1.PCCNTR.8858652,31500000.0,terminado
25,CO1.REQ.6412000,CO1.BDOS.6285495,Seleccionado,0,CO1.PCCNTR.6455391,13800000.0,Cerrado
31,CO1.REQ.6303012,CO1.BDOS.6180457,Seleccionado,0,CO1.PCCNTR.6375373,21600000.0,Cerrado
32,CO1.REQ.3455117,CO1.BDOS.3365481,Seleccionado,0,CO1.PCCNTR.4097358,18300000.0,Cerrado
40,CO1.REQ.5569639,CO1.BDOS.5452450,Seleccionado,0,CO1.PCCNTR.5765032,21596904.0,Cerrado
41,CO1.REQ.1612007,CO1.BDOS.1562827,Seleccionado,0,CO1.PCCNTR.1996941,2979000.0,Cerrado
42,CO1.REQ.2843796,CO1.BDOS.2767361,Seleccionado,0,CO1.PCCNTR.3516271,16216200.0,Cerrado
43,CO1.REQ.5747669,CO1.BDOS.5630932,Seleccionado,0,CO1.PCCNTR.5931957,10800000.0,En ejecución
44,CO1.REQ.377073,CO1.BDOS.367988,Seleccionado,0,CO1.PCCNTR.363356,27007865.0,Aprobado
45,CO1.REQ.7988423,CO1.BDOS.7849421,Seleccionado,0,CO1.PCCNTR.7676178,22376667.0,Modificado

### Inconsistencia 2: Diferencia entre el valor de adjudicación y el valor del contrato

Durante la revisión del dataset integrado se identificaron **18.330 registros (81,14 % del total)** en los que `valor_total_adjudicacion` es igual a cero, mientras que `valor_del_contrato` tiene un valor positivo.

Esta situación se observó en registros con diferentes estados del procedimiento y del contrato, por lo que es necesario revisar el significado de ambos campos y contrastar la información con las fuentes originales de SECOP II.

**Tratamiento:** los registros se conservarán sin reemplazar los ceros ni eliminar filas. La discrepancia se documentará para su verificación posterior.

**Justificación:** las dos columnas provienen de fuentes distintas y pueden representar conceptos o etapas diferentes. Modificar una columna para hacerla coincidir con la otra sin verificar su significado podría introducir errores en el análisis de los montos de contratación.

In [ ]:
dataset_final["revision_valores"] = (
    (dataset_final["valor_total_adjudicacion"] == 0) &
    (dataset_final["valor_del_contrato"] > 0)
)

print("Registros marcados para revisión:")
print(dataset_final["revision_valores"].sum())

display(
    dataset_final.loc[
        dataset_final["revision_valores"],
        [
            "id_contrato",
            "valor_total_adjudicacion",
            "valor_del_contrato",
            "revision_valores"
        ]
    ].head(10)
)

Registros marcados para revisión:
18330

,id_contrato,valor_total_adjudicacion,valor_del_contrato,revision_valores
0,CO1.PCCNTR.5428644,0,436272918.0,True
4,CO1.PCCNTR.4459047,0,14400000.0,True
5,CO1.PCCNTR.6867266,0,6125793.0,True
6,CO1.PCCNTR.9204373,0,30000000.0,True
23,CO1.PCCNTR.4499020,0,21301000.0,True
24,CO1.PCCNTR.8858652,0,31500000.0,True
25,CO1.PCCNTR.6455391,0,13800000.0,True
31,CO1.PCCNTR.6375373,0,21600000.0,True
32,CO1.PCCNTR.4097358,0,18300000.0,True
40,CO1.PCCNTR.5765032,0,21596904.0,True

In [ ]:
for columna in [
    "precio_base",
    "valor_total_adjudicacion",
    "valor_del_contrato"
]:
    print(
        f"{columna}:",
        (dataset_final[columna] < 0).sum(),
        "valores negativos"
    )

precio_base: 0 valores negativos
valor_total_adjudicacion: 0 valores negativos
valor_del_contrato: 0 valores negativos

### Conclusiones de la calidad de datos

En esta etapa se revisaron los tipos de datos, los valores faltantes, las fechas de los contratos y los importes económicos del dataset integrado de SECOP II.

En primer lugar, las cuatro columnas de fechas se convirtieron al tipo `datetime64[ns]`, mientras que `precio_base`, `valor_total_adjudicacion` y `valor_del_contrato` se transformaron a tipos numéricos. Se conservaron los valores faltantes que ya existían en las fechas, sin sustituirlos automáticamente.

En segundo lugar, se identificaron dos contratos con fechas de finalización anteriores a las fechas de inicio. Estos registros se marcaron para verificación, debido a que no se dispone de evidencia suficiente para determinar qué fecha debería corregirse.

También se identificaron 18.330 registros, equivalentes al 81,14 % del dataset, con un valor de adjudicación igual a cero y un valor de contrato positivo. Esta diferencia se documentó como una discrepancia pendiente de validación con las fuentes originales, sin reemplazar los valores ni eliminar registros.

Finalmente, no se encontraron importes negativos en las tres columnas económicas revisadas.

Como resultado, se mejoró la consistencia de los tipos de datos y se identificaron situaciones que deben verificarse antes de realizar análisis estadísticos o formular conclusiones sobre la contratación pública.

**Decisión general:** conservar los registros originales, documentar los hallazgos y evitar correcciones que no estén respaldadas por la información de las fuentes.

In [ ]:
print("Tamaño actual:", dataset_final.shape)

print(
    "Contratos con fechas invertidas:",
    dataset_final["fecha_invertida"].sum()
)

print(
    "Registros con discrepancia de importes:",
    dataset_final["revision_valores"].sum()
)

Tamaño actual: (22591, 24)
Contratos con fechas invertidas: 2
Registros con discrepancia de importes: 18330